# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


require Pod::Executable.execute_command('node', ['-p',
'require.resolve(
  "react-native-permissions/scripts/setup.rb",
  {paths: [process.argv[1]]},
)', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Firebase Swift 모듈 지원을 위한 설정
# use_modular_headers!
use_frameworks! :linkage => :dynamic # 동적 프레임워크 사용
# use_frameworks!: linkage => :static
#linkage = ENV['USE_FRAMEWORKS']
#if linkage != nil
#  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#  use_frameworks! :linkage => linkage.to_sym
#end

target 'FuneralProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'RNNotifee', :path => '../node_modules/@notifee/react-native'

  setup_permissions([
    'Camera',
    'PhotoLibrary',
    'PhotoLibraryAddOnly'
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
